### ISSUE TITLE
Trouble connecting to Apollo

### ISSUE THREAD

**Issue by aleks-rope** [Promises/refactored-client-377#9]
I'm having trouble connecting this to my Apollo server. 

I updated the keys however it seems like the client is not connecting to the server.

-I have generated the keys using the RSAKeygenerator.java file in Apollo.
-I have moved the public keys to the config file.
-I have renamed the config file as instructed.
-Im using 377 cache.

My Apollo server has 0 failures so I think it's something on the client's end.

Is there anything else I can do to troubleshoot this issue?

**Comment by Promises** [comment]
I will do some tests and report back

**Comment by Promises** [comment]
could you try now?, there was an issue relating to the password input.

**Comment by aleks-rope** [comment]
Thanks for looking into this. It appears that I'm still having trouble logging in. 

Here is the error I'm getting on client (no errors on server side).
<img width="929" alt="Screen Shot 2020-02-17 at 16 48 46" src="https://user-images.githubusercontent.com/58922379/74633749-ad780880-51a5-11ea-9e4d-1ca5fa791294.png">

Let me confirm it with another client just to be sure and report back.

**Comment by Promises** [comment]
That seems like a weird login response, you can hit me up on discord if you would like "Henning B#4920"

**Comment by aleks-rope** [comment]
@Promises Thank you for helping me resolve this issue over discord. Just to recap the issue was resolved by enabling `JAGGRAB` to `true` instead of `false`. Thanks again!
